services:
  app:
    build: ./php74-alpine
    volumes:
      - ./www:/var/www
    ports:
      - 8003:8000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shares
    
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - share-laravel-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shares
      POSTGRES_USER: root

volumes:
  share-laravel-postgres-data: